<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('include/css/style.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('include/js/bootstrap/bootstrap.min.js'))
            ->prependFile($this->basePath('include/js/jquery/jquery-1.11.3.min.js'))
            ->prependFile($this->basePath('include/js/page/ctrl.js'))
        ; ?>

    </head>
    <body>
       
            <?php print_r($this->content); ?>
            
    </body>
</html>
